(ns hrest.Position
  (:require [hrest.Types :refer :all])
  (:require [clojure.core.typed :as t :refer [check-ns]]))
(set! *warn-on-reflection* true)

(t/ann NW (t/Val ::NW))
(def NW ::NW)
(t/ann N (t/Val ::N))
(def N ::N)
(t/ann NE (t/Val ::NE))
(def NE ::NE)
(t/ann W (t/Val ::W))
(def W ::W)
(t/ann C (t/Val ::C))
(def C ::C)
(t/ann E (t/Val ::E))
(def E ::E)
(t/ann SW (t/Val ::SW))
(def SW ::SW)
(t/ann S (t/Val ::S))
(def S ::S)
(t/ann SE (t/Val ::SE))
(def SE ::SE)

(t/defalias Position
  (t/U (t/Val ::NW) (t/Val ::N) (t/Val ::NE)
       (t/Val ::W)  (t/Val ::C) (t/Val ::E)
       (t/Val ::SW) (t/Val ::S) (t/Val ::SE)))

(defmethod show NW [p] "NW")
(defmethod show N  [p] "N ")
(defmethod show NE [p] "NE")
(defmethod show E  [p] "E ")
(defmethod show SE [p] "SE")
(defmethod show S  [p] "S ")
(defmethod show SW [p] "SW")
(defmethod show W  [p] "W ")
(defmethod show C  [p] "C ")
